Feature/add a search component and implement it in the students view
alexesba/schoolapp-ui pull request #4
Opened 2024-03-05 04:48 UTC by jnegrete

This Change adds the search functionality to the Students view, using the full name

https://github.com/alexesba/schoolapp-ui/assets/4744682/428ced95-085f-4c40-9fe0-0f9faa3a907c

2024-03-06 03:50 UTC, alexesba requested changes
Te deje  pequeños comentarios para mejorar la funcionalidad del componente. 
Igual alguna sugerencia no mencionada anteriormente el ticket pero si se sale del alcance del ticket igual lo implementamos en otro ticket. 
Si tienes preguntas con confianza ok. saludos

2024-03-06 03:50 UTC, alexesba commented on src/jsx/components/Pagination/Search.jsx
> +      <input type="text" className="form-control"
Creo que deberíamos usar `controlled components` 
https://legacy.reactjs.org/docs/glossary.html#controlled-vs-uncontrolled-components

2024-03-06 03:50 UTC, alexesba commented on src/jsx/components/Pagination/Search.jsx
> +      <input type="text" className="form-control"
Estaba pensando que quizá deberíamos llamar la función de buscar cuando el usuario deje de escribir y pase 1 o 2 segundos. Pero esto lo dejo a consideración ya que no estaba descrito en el ticket.

2024-03-06 03:50 UTC, alexesba commented on src/jsx/components/Pagination/Search.jsx
> +    if ([1, 2].includes(text.length) == false) {
Creo que aquí podría ser más simple la condición. 
```suggestion
    if (text.length >= 1) {
```
Aunque de preferencia podría ser mejor usar la condición `>= 2`

2024-03-06 03:50 UTC, alexesba commented on src/jsx/components/Student/Students.jsx
> +    getAll({ q: query, page: currentPage, order: sortOrder });
aquí podríamos evitar mandar el parámetro q con la cadena vacía. 
```suggestion
let params = { page: currentPage, order: sortOrder }

if (query.length) {
   params = {...params, q: query }
} 
getAll(params);
```

2024-03-06 03:50 UTC, alexesba commented on src/jsx/components/Pagination/Search.jsx
> +      <input type="text" className="form-control"
como el padre es quien tiene el valor de la busqueda `query` solo haría falta poner el valor `value = {query}`en este componente. Si tienes dudas me pregutas.

2024-03-06 04:15 UTC, jnegrete commented on src/jsx/components/Pagination/Search.jsx
> +    if ([1, 2].includes(text.length) == false) {
pero al usar `>= 2`  no haría la busqueda al borrar todo el texto, nos haría falta agregar un or

2024-03-07 21:26 UTC, alexesba approved these changes
LGTM

2024-03-07 21:26 UTC, merged